### ISSUE TITLE
Issues with `markdown-link-check-disable-next-line`

### ISSUE THREAD

**Issue by mapachurro** [Consensys/doc.linea#462] opened 2024-03-06 13:09 UTC
in `index.mdx` within `/docs/build-on-linea/linea-version`, the markdown link check escape tags are throwing errors.

I'm going to comment them out, for now. This seems to be a misalignment between tooling, ie, how does the link checker parse HTML in an MDX context.

![image](https://github.com/Consensys/doc.zk-evm/assets/7252642/0c5d1f3f-bea7-4f0e-a05f-658a2c30d411)

**Comment by jlwllmr** [comment] 2024-03-07 16:29
I _think_ it might have been me who deliberately added these. In some cases it's the only way to get the link linter to pass. The root cause is the linter, as since it throws errors for functional links, we're left with two choices:

1. Ignore the failed linter, double check the links it identifies as broken do actually work, and merge anyway
2. Add these ^ commands to pages that throw errors to enable the linter to pass, but break the formatting.

**Comment by bgravenorst** [comment] 2024-03-14 00:27
Yeah I've also added them for the same reason mentioned by Joel. Sometimes I use it because some websites block the job from checking (probably with DDOS protection).

**Comment by bgravenorst** [comment] 2024-03-14 03:39
@mapachurro and @jlwllmr this solution using a config file appears to work:
https://github.com/Consensys/doc.zk-evm/pull/476

Let me know if you are happy with me to implement it. Also there are quite a few Twitter URLs that required this tag. Should we include that?

**Comment by jlwllmr** [comment] 2024-03-28 13:02
@bgravenorst @mapachurro given we merged the solution, can we close this issue?

**Comment by jlwllmr** [comment] 2024-06-05 15:23
Closing as this was fixed a while ago.

**Closed by jlwllmr** 2024-06-05 15:23 UTC
